[package]
name = "sentinel_core"
version = "2.2.0"
edition = "2021"
authors = ["Mukti-Sys <sentinel@mukti-sys.org>"]
description = "Native high-performance acceleration core for Sentinel Antivirus"
license = "MIT"

[lib]
name = "sentinel_core"
crate-type = ["cdylib", "rlib"]

[dependencies]
sha2 = "0.10"
md-5 = "0.10"
rayon = "1.10"
walkdir = "2.5"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
